version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/nginx/log:/var/log/nginx
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  blue-api:
    container_name: blue-api
    image: goodmoneying/server
    ports:
      - 8080:8080

    restart: "always"

  green-api:
    container_name: green-api
    image: goodmoneying/server
    ports:
      - 8080:8080
    restart: "always"

  batch:
    container_name: batch
    image: goodmoneying/batch
    restart: "always"

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
