version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/nginx/log:/var/log/nginx
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - "server"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  server:
    container_name: server
    image: goodmoneying/server
    environment:
      - DB_HOSTNAME=${{ secrets.DB_HOSTNAME }}
      - DB_DATABASE=${{ secrets.DB_DATABASE }}
      - DB_USERNAME=${{ secrets.DB_USERNAME }}
      - DB_PASSWORD=${{ secrets.DB_PASSWORD }}
      - OPENAI_BASE_URL=${{ secrets.OPENAI_BASE_URL }}
      - OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
      - CLOUD_AWS_S3_BUCKET=${{ secrets.CLOUD_AWS_S3_BUCKET }}
      - CLOUD_AWS_STACK_AUTO=${{ secrets.CLOUD_AWS_STACK_AUTO }}
      - CLOUD_AWS_REGION_STATIC=${{ secrets.CLOUD_AWS_REGION_STATIC }}
      - CLOUD_AWS_CREDENTIALS_ACCESSKEY=${{ secrets.CLOUD_AWS_CREDENTIALS_ACCESSKEY }}
      - CLOUD_AWS_CREDENTIALS_SECRETKEY=${{ secrets.CLOUD_AWS_CREDENTIALS_SECRETKEY }}
      - NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}
      - NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }}
      - NAVER_BASE_URL=${{ secrets.NAVER_BASE_URL }}
    ports:
      - "8080:8080"
    restart: "always"

  batch:
    container_name: batch
    image: goodmoneying/batch
    environment:
      - DB_HOSTNAME=${{ secrets.DB_HOSTNAME }}
      - DB_DATABASE=${{ secrets.DB_DATABASE }}
      - DB_USERNAME=${{ secrets.DB_USERNAME }}
      - DB_PASSWORD=${{ secrets.DB_PASSWORD }}
      - OPENAI_BASE_URL=${{ secrets.OPENAI_BASE_URL }}
      - OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
      - CLOUD_AWS_S3_BUCKET=${{ secrets.CLOUD_AWS_S3_BUCKET }}
      - CLOUD_AWS_STACK_AUTO=${{ secrets.CLOUD_AWS_STACK_AUTO }}
      - CLOUD_AWS_REGION_STATIC=${{ secrets.CLOUD_AWS_REGION_STATIC }}
      - CLOUD_AWS_CREDENTIALS_ACCESSKEY=${{ secrets.CLOUD_AWS_CREDENTIALS_ACCESSKEY }}
      - CLOUD_AWS_CREDENTIALS_SECRETKEY=${{ secrets.CLOUD_AWS_CREDENTIALS_SECRETKEY }}
      - NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}
      - NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }}
      - NAVER_BASE_URL=${{ secrets.NAVER_BASE_URL }}
    restart: "always"

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot


  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm  # 공유 메모리를 위한 설정

networks:
  default:
    driver: bridge