spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/database/kusitms

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

crawling:
  driver_path: ${ CRAWLING_DRIVER_PATH }
  target-url: ${ TARGET_URL }

open-ai:
  endpoint : ${ OPEN_AI_API_END_POINT }
  secret-key : ${ OPEN_AI_SECRET_KEY }