spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-good-moneying.c9g0uuc6uk51.ap-northeast-2.rds.amazonaws.com/newthink
    username: admin
    password: good1234
  sql:
    init:
      platform: mysql

  jpa:
    hibernate:
      ddl-auto: create # create-drop, update, validate, none
    properties:
      hibernate:
        format_sql: true # SQL 포맷팅
        show_sql: true # SQL 출력
        dialect: org.hibernate.dialect.MySQL8Dialect

  batch:
    jdbc:
      initialize-schema:
    job:
      enabled: true
jwt:
  secret-key: NiOeyFbN1Gqo10bPgUyTFsRMkJpGLXSvGP04eFqj5B30r5TcrtlSXfQ7TndvYjNvfkEKLqILn0j1SmKODO1Yw3JpBBgI3nVPEahqxeY8qbPSFGyzyEVxnl4AQcrnVneI
  issuer: duduk.shop
  access:
    expiration: 3600000 # 1시간 (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    header: Authorization
  refresh:
    expiration: 1209600000 # 2주 (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization-refresh


crawling:
  driver_path: "/Users/kwonminhyeok/Downloads/chromedriver_mac_arm64/chromedriver"
  target-url: "https://www.hankyung.com/all-news"

open-ai:
  end-point: "https://api.openai.com/v1/chat/completions"
  secret-key: "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"


cloud:
  aws:
    s3:
      bucket: "goodmoneying"
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: "AKIAYS2NV5RSG2UYIRSY"
      secretKey: "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"

naver:
  client-id: iboe5ch6oi
  client-secret: 35GkUOob92lG6b1uipAf5gUW5JaETGCPTAf7ax9Z


selenium:
  url: "http://selenium:4444/wd/hub"
