springdoc:
  swagger-ui:
    # Swagger UI 페이지에 대한 경로
    path: /swagger-ui.html
    # Group 별 정렬 기준 (ASC 오름차순, DESC 내림차순)
    groups-order: DESC
    # API 목록 내 정렬 기준 (method, alpha)
    operationsSorter: method
    # Swagger UI가 로드될 때 기본적으로 제공하는 예제 URL 생략
    disable-swagger-default-url: true
    # API 요청 시 실행 시간을 표시
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/v1/**