name: Backend Server CI  
  
on:  
  push:
    branches:
      - main
      
  pull_request:  
    branches:  
      - main  
      - develop  

    types: [opened, synchronize]
  
jobs:  
  build:  
    runs-on: ubuntu-22.04  
  
    steps:  
      - name: action checkout  
        uses: actions/checkout@v3  
  
      - name: Set up JDK 17  
        uses: actions/setup-java@v3  
        with:  
          java-version: '17'  
          distribution: 'temurin'  
  
      - name: Grant execute permission for gradlew  
        run: chmod +x gradlew

      - name: Set up environment variables
        run: |
          echo "secrets.openai.base-url=${{ secrets.OPENAI_BASE_URL }}" >> $GITHUB_ENV
          echo "secrets.openai.api-key=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          echo "secrets.cloud.aws.s3.bucket=${{ secrets.CLOUD_AWS_S3_BUCKET }}" >> $GITHUB_ENV
          echo "secrets.cloud.aws.stack.auto=${{ secrets.CLOUD_AWS_STACK_AUTO }}" >> $GITHUB_ENV
          echo "secrets.cloud.aws.region.static=${{ secrets.CLOUD_AWS_REGION_STATIC }}" >> $GITHUB_ENV
          echo "secrets.cloud.aws.credentials.access-key=${{ secrets.CLOUD_AWS_CREDENTIALS_ACCESSKEY }}" >> $GITHUB_ENV
          echo "secrets.cloud.aws.credentials.secret-key=${{ secrets.CLOUD_AWS_CREDENTIALS_SECRETKEY }}" >> $GITHUB_ENV
          echo "secrets.naver.client-id=${{ secrets.NAVER_CLIENT_ID }}" >> $GITHUB_ENV
          echo "secrets.naver.client-secret=${{ secrets.NAVER_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "secrets.naver.base-url=${{ secrets.NAVER_BASE_URL }}" >> $GITHUB_ENV
      

      - name: Run tests with Gradle
        env:
          SPRING_PROFILES_ACTIVE: test
        run: ./gradlew test
