name: Backend Server CI  
  
on:  
  push:
    branches:
      - main
      
  pull_request:  
    branches:  
      - main  
      - develop  

    types: [opened, synchronize]
  
jobs:  
  build:  
    runs-on: ubuntu-22.04  
  
    steps:  
      - name: action checkout  
        uses: actions/checkout@v3  
  
      - name: Set up JDK 17  
        uses: actions/setup-java@v3  
        with:  
          java-version: '17'  
          distribution: 'temurin'  
  
      - name: Grant execute permission for gradlew  
        run: chmod +x gradlew  

      - name: Run tests with Gradle
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://db-good-moneying.c9g0uuc6uk51.ap-northeast-2.rds.amazonaws.com/newthink
          SPRING_DATASOURCE_USERNAME: admin
          SPRING_DATASOURCE_PASSWORD: good1234
        run: ./gradlew test
